-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 17:04:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema examen3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examen3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examen3` DEFAULT CHARACTER SET utf8 ;
USE `examen3` ;

-- -----------------------------------------------------
-- Table `examen3`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen3`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `latitud` VARCHAR(100) NOT NULL,
  `longitud` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `examen3`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen3`.`pedido` (
  `idpedido` INT(11) NOT NULL AUTO_INCREMENT,
  `fechahoraregistro` DATETIME NOT NULL,
  `fechahoraentrega` DATETIME NOT NULL,
  `cliente_idcliente` INT(11) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `examen3`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `examen3`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen3`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `url` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `examen3`.`pedido_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen3`.`pedido_has_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_idpedido` INT(11) NOT NULL,
  `producto_idproducto` INT(11) NOT NULL,
  INDEX `fk_pedido_has_producto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_pedido_has_producto_pedido_idx` (`pedido_idpedido` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_has_producto_pedido`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `examen3`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `examen3`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
