package com.everist.examentres.pedidos.model;
// Generated 27/09/2019 01:24:25 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "examen3")
public class Cliente implements java.io.Serializable {

	private int idcliente;
	private String nombre;
	private String latitud;
	private String longitud;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
	}

	public Cliente(int idcliente, String nombre, String latitud, String longitud) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public Cliente(int idcliente, String nombre, String latitud, String longitud, Set<Pedido> pedidos) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.latitud = latitud;
		this.longitud = longitud;
		this.pedidos = pedidos;
	}

	@Id

	@Column(name = "idcliente", unique = true, nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "latitud", nullable = false, length = 100)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, length = 100)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
