package com.everist.examentres.pedidos.model;
// Generated 27/09/2019 01:24:25 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "examen3")
public class Pedido implements java.io.Serializable {

	private int idpedido;
	private Cliente cliente;
	private Date fechahoraregistro;
	private Date fechahoraentrega;
	@JsonIgnore
	private Set<PedidoHasProducto> pedidoHasProductos = new HashSet<PedidoHasProducto>(0);

	public Pedido() {
	}

	public Pedido(int idpedido, Cliente cliente, Date fechahoraregistro, Date fechahoraentrega) {
		this.idpedido = idpedido;
		this.cliente = cliente;
		this.fechahoraregistro = fechahoraregistro;
		this.fechahoraentrega = fechahoraentrega;
	}

	public Pedido(int idpedido, Cliente cliente, Date fechahoraregistro, Date fechahoraentrega,
			Set<PedidoHasProducto> pedidoHasProductos) {
		this.idpedido = idpedido;
		this.cliente = cliente;
		this.fechahoraregistro = fechahoraregistro;
		this.fechahoraentrega = fechahoraentrega;
		this.pedidoHasProductos = pedidoHasProductos;
	}

	@Id

	@Column(name = "idpedido", unique = true, nullable = false)
	public int getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(int idpedido) {
		this.idpedido = idpedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(int i) {
		this.cliente = i;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahoraregistro", nullable = false, length = 19)
	public Date getFechahoraregistro() {
		return this.fechahoraregistro;
	}

	public void setFechahoraregistro(Date fechahoraregistro) {
		this.fechahoraregistro = fechahoraregistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahoraentrega", nullable = false, length = 19)
	public Date getFechahoraentrega() {
		return this.fechahoraentrega;
	}

	public void setFechahoraentrega(Date fechahoraentrega) {
		this.fechahoraentrega = fechahoraentrega;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<PedidoHasProducto> getPedidoHasProductos() {
		return this.pedidoHasProductos;
	}

	public void setPedidoHasProductos(Set<PedidoHasProducto> pedidoHasProductos) {
		this.pedidoHasProductos = pedidoHasProductos;
	}

}
